SHM part 2
coders-school/object-oriented-programming pull request #105
Opened 2021-08-15 19:11 UTC by NikczemnyOkularnik

@Kasia9311  @kondorski  @Crazyayane07  @pwiatr3 @NikczemnyOkularnik

2021-08-23 12:00 UTC, nauka-programowania-MA requested changes

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Game.cpp
> +    , playerOne_(new Player(std::make_unique<Ship>(20, 30, 10, "Dar Pomorza", 3, time_), 1000, 1000))
I think all should be constexpr variables

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Game.cpp
> +        if (playerOne_->getMoney() < 0 || time_->getCurrentTime() >= gameDays_)
else if

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Game.cpp
> +        if (quitRequest)
else if

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Game.cpp
> +    }while(!quitRequest);
you always quit earlier in if (quitRequest). So here it is redundant.

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Game.cpp
> +    std::cin >> i;
What when someone provides the wrong input? Like "Ala ma kota"

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Game.cpp
> +    playerOne_->getShip()->shipCargo.push_back(new Item("Hook", 1, 100, time_, Rarity::common));
"new" is depreciated. Please use make_shared/ make_unique.

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Game.cpp
> +    std::cin >> cargoElement;
validate input

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Game.cpp
> +    std::cin >> cargoElement;
same here

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Map.cpp
> +        Coordinates c ((float)distrib(gen), (float)distrib(gen));
don't use "C style" cast, use static_cast instead

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Map.cpp
> +    auto distance = sqrt(pow((disX-distanceX), 2) + pow((disY - distanceY),2));
make it const

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Map.cpp
> +size_t Map::calculateDistance(Island island_pos_)
seems like const method

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Map.cpp
> +bool Map::contains(const std::vector<Coordinates>& vec, const Coordinates& c) {
const method

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Map.cpp
> +void Map::PrintCurrentPosition()
cont method

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Map.cpp
> +void Map::DebugPrintIsland () {
cont method

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Map.hpp
> +//class Island;
?

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Map.hpp
> +    Island* getCurrentPos() {return current_pos_;}
cont method

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Map.hpp
> +    friend class Game;
don't mix function with friend declaration

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Menu.cpp
> +        std::cout << "Wrong answer, please use numbers 0 - 5" << '\n';
Nice. Do the same in others input method

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Menu.hpp
> +    void playerChoice();
I guess most of them could be const

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Storable.cpp
> +}
?

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Storable.hpp
> +        }
move C'tor definition to .cpp

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +std::vector<Rarity> rarityChoice = {Rarity::common, Rarity::rare, Rarity::epic, Rarity::legendary};
make it constexpr array.
Instad strign use array<const* char>

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +    size_t alcoholPercentage = percentage(gen);
const

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +
const

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +Cargo * Store::findMatchCargo(Cargo * cargo)
const method

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +    return nullptr;
?

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +    for (auto el : storeCargo)
here you copy

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +        el->reduceAmount(1);
and work on copy

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +    }
if you need index in loop, use old loop instead. for(int i = 0....)

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +    auto storeCargoAmount = findMatchCargo(item)->getAmount();
const

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +    }
return here and remove else

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +    else
return form if and remove else

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.cpp
> +    auto cargoPtr = findMatchCargo(item);
const

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.hpp
> +//class Cargo;
?

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.hpp
> +enum class Response
Move to class

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.hpp
> +    void printStoreCargo();
should be const method

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Store.hpp
> +    }
move definition to .cpp

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Time.cpp
> +    list_observer_.remove(observer);
You should attach/ dettach in D'tor. Use RAII pattern

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/Time.cpp
> +    }
Do not copy

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/TimeEffectable.hpp
> +    virtual void nextDay(size_t) {}
Add virtual D'tor when you have virtual method

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/fruit.cpp
> +}
Yup, attach in detach in C'tor/ D'tor

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/fruit.cpp
> +    // this->time_.detach(this);
You have crash, here because you didn't attach observer in C'tor, you only wanted to remove it here

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/ship.cpp
> +    time_->attach(this);
This is wrong! You attach twice the same observer!!!

Please attach it in one C'tor, and rest C'tors will call this one

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/ship.cpp
> +        shipCargo.emplace_back(item);
push_back, use emplace when you pass arguments to C'tro, here you use copy C'tor or Move C'tor.

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/ship.cpp
> +    auto shipCargoAmount = findMatchCargo(item)->getAmount();
const

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/ship.cpp
> +        auto it = std::find_if(begin(shipCargo), end(shipCargo), [item](const auto* el){ return *el == *item; });
const

2021-08-23 12:00 UTC, nauka-programowania-MA commented on shm/ship.cpp
> +        }
new is deprecated. Please create 'clone()` method to cargo, which will clone itself and return unique_ptr to the new object. When you do this, you avoid ugly dynamic_cast which in 95% show the wrong style of code.

`const auto* toAdd = loadCargo->clone()`

2021-09-07 18:47 UTC, Kasia9311 commented on shm/Game.cpp
> +    std::cin >> cargoElement;
PR 6e5d003

2021-09-07 18:47 UTC, ziobron commented
Thanks @Kasia9311 for Code Review.
🏅 1 XP granted

2021-09-07 18:48 UTC, Kasia9311 commented on shm/Game.cpp
> +    std::cin >> cargoElement;
PR 6e5d003

2021-09-07 18:48 UTC, ziobron commented
Thanks @Kasia9311 for Code Review.
🏅 1 XP granted

2021-09-07 18:54 UTC, Kasia9311 commented on shm/Game.cpp
> +        if (quitRequest)
PR e150a0e

2021-09-07 18:54 UTC, ziobron commented
Thanks @Kasia9311 for Code Review.
🏅 1 XP granted

2021-09-07 18:55 UTC, Kasia9311 commented on shm/Game.cpp
> +        if (playerOne_->getMoney() < 0 || time_->getCurrentTime() >= gameDays_)
PR e150a0e

2021-09-07 19:12 UTC, Kasia9311 commented on shm/Game.cpp
> +    }while(!quitRequest);
PR cf1bed7

2021-09-07 19:27 UTC, Kasia9311 commented on shm/Game.cpp
> +    std::cin >> i;
PR 681f9f0

2021-09-07 19:50 UTC, Kasia9311 commented on shm/Map.cpp
> +    auto distance = sqrt(pow((disX-distanceX), 2) + pow((disY - distanceY),2));
PR 08f0381

2021-09-10 09:40 UTC, ziobron reviewed
Just checking automation

2021-09-10 09:40 UTC, ziobron commented
Thanks @ziobron for Code Review.
🏅 1 XP granted

2021-09-10 09:41 UTC, ziobron reviewed
Quick additional check

2021-09-10 09:42 UTC, ziobron reviewed
And the last check

2021-09-10 09:42 UTC, ziobron commented
Thanks @ziobron for Code Review.
🏅 1 XP granted

2021-11-02 08:07 UTC, nauka-programowania-MA approved these changes

2021-11-02 08:07 UTC, nauka-programowania-MA commented on shm/Game.cpp
> +        std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
This is repeated few times, maybe create function `clearInputStream()`? 
DRY rule -> don't repeat yourself :)

2021-11-02 08:07 UTC, nauka-programowania-MA commented on shm/alcohol.cpp
> +    return new Alcohol(*this);
Avoid raw ptr! and new operator

return std::unique_ptr<Cargo> and use std::make_unique.

2021-11-02 08:07 UTC, nauka-programowania-MA commented on shm/fruit.cpp
> +    //return static_cast<size_t>(basePrice_ * ((size_t)(expiry_date_ - time_elapsed_)) / expiry_date_);
remove commented code. 
This commented code looks good, why do you return basePrice_ instead?

2021-11-02 08:07 UTC, nauka-programowania-MA commented on shm/fruit.cpp
> +    return new Fruit(*this);
unique_ptr

2021-11-02 08:07 UTC, nauka-programowania-MA commented on shm/item.cpp
> +    return new Item(*this);
unique_ptr

2021-11-02 08:07 UTC, nauka-programowania-MA commented on shm/ship.cpp
> +    if(cargoPtr)
Better
```
if (cargoPtr = findMatchCargo(item)) {

}
```
If automatically check if this is not nullptr

2021-11-02 08:07 UTC, nauka-programowania-MA commented on shm/ship.cpp
> +        // }
Remove commented code

2022-01-21 12:35 UTC, nauka-programowania-MA approved these changes

2022-01-21 12:35 UTC, nauka-programowania-MA commented on shm/Map.cpp
> +        int y = (int)distrib(gen);
we should avoid old (C) style casting. Because it unsafe

2022-01-21 12:35 UTC, nauka-programowania-MA commented on shm/Map.cpp
> +    for (int i = 0; i < (int)constVariables::ISLANDS_COUNT; i++)
better size_t i = 0 and don't cast to int

2022-01-21 12:35 UTC, nauka-programowania-MA commented on shm/Map.cpp
> +            y = (int)distrib(gen);
avoid old (C) style casting

2022-01-21 12:35 UTC, closed without merging