Homework 2 SHM
coders-school/object-oriented-programming pull request #56
Opened 2020-07-05 13:34 UTC by anraf1001

Authors: @Vicx95, @kontrybutor, @piezol, @kari0036, @anraf1001

2020-07-06 12:25 UTC, nauka-programowania-MA requested changes
Please fix issues and the make new pull request without 301 files. This is really hard to read.

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/alcohol.hpp
> +    Cargo& operator-=(size_t amount) override;
This is also override from Cargo

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/alcohol.hpp
> +    Cargo* cloneToRawPointer() override { return new Alcohol(*this); }
Dangerous. You allocate memory and need to manage it. You can clone as shared_ptr.

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/cloneable.hpp
> +    }
when `cloneToRawPtr` will be replaced as cloneAsSharedPtr you can ommit static_cast.

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/delegate.hpp
> +};
Delegate should not be standalone class. You can create a lot of delegates and then you have conflict with names.

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/fruit.hpp
> +    Cargo* cloneToRawPointer() override { return new Fruit(*this); }
cloneToSharedPtr

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/item.hpp
> +    Cargo& operator-=(size_t amount) override;
also override from Cargo

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/item.hpp
> +    Cargo* cloneToRawPointer() override { return new Item(*this); }
shared_ptr

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/item.hpp
> +                                                     {Rarity::legendary, 8}};
you can use enum number as price. Common = 1, rare = 2, epic = 4 etc...

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/observer.hpp
> +};
Observer should not be as standalone class. You can create a lot of observers.

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/player.hpp
> +    void clearEmptyCargos() override { ship_->clearEmptyCargos(); }
to cpp. This is not setter or getter

2020-07-06 12:25 UTC, nauka-programowania-MA commented on shm/inc/store.hpp
> +    Time* time_;
You don't need pointer to Time*. You have service locator, so you can always use getTime(). What's more You can provide different time to locator, and then you will use wrong or deleted ptr.

2020-07-07 11:16 UTC, WBigaj reviewed
Are these 301 files really neccessary. It's hard to dig through it to find relevant code.

2020-07-17 13:32 UTC, nauka-programowania-MA approved these changes

2020-07-17 13:32 UTC, nauka-programowania-MA commented on shm/inc/alcohol.hpp
> +    std::shared_ptr<Cargo> getShared() override { return std::make_shared<Alcohol>(Alcohol(*this)); }
maybe just clone?

2020-07-17 13:32 UTC, nauka-programowania-MA commented on shm/inc/cargo.hpp
> +    virtual ~Cargo() = default;
= default is also definition. Move to cpp

2020-07-17 13:32 UTC, nauka-programowania-MA commented on shm/inc/dryfruit.hpp
> +    // override from Cargo.Fruit
Just Fruit

2020-07-17 13:32 UTC, nauka-programowania-MA commented on shm/inc/player.hpp
> +    std::shared_ptr<Cargo> getCargo(size_t index) const { return ship_->getCargo(index); }
Are You validate somewhere index?

2020-07-17 13:32 UTC, nauka-programowania-MA commented
{
"requirement_ids": [2568, 2568, 2568, 2571, 2571, 2571, 2569, 2570],
"points": [5, 5, 5, 8, 8, 8, 20, 6],
"users": ["Vicx95", "kontrybutor", "piezol", "kari0036", "anraf1001"]
}

2020-07-17 13:44 UTC, closed without merging