normalizacja i ujednolicanie
coders-school/object-oriented-programming pull request #80
Opened 2020-08-22 07:42 UTC by MrMijagi

2020-08-22 09:17 UTC, WBigaj reviewed
Sprawdziłem poprawki i mam pytanie.

2020-08-22 09:17 UTC, WBigaj commented on README.md
> +### [The four pillars of objectivity](module4/pillars.md)
Czemu tu nagle zmieniamy styl z polskich nazw na angielskie?

2020-08-24 10:05 UTC, Penthurion reviewed
Brak zastrzeżeń i sugestii :+1:

2020-08-25 19:21 UTC, nauka-programowania-MA approved these changes

2020-08-26 07:58 UTC, ziobron requested changes
Zmień proszę shm tak jak był, czyli od razu bezpośrednio a nie w module1/homework. To jest większy projekt, wiec tutaj wyjątkowo chcemy go mieć oddzielnie.

2020-08-26 07:58 UTC, ziobron commented on README.md
> +### [The four pillars of objectivity](module4/pillars.md)
4 filary obiektowości

2020-08-26 07:58 UTC, ziobron commented on README.md
> +### [The four pillars of objectivity](module4/pillars.md)
Tak, w readme niech wszystko będzie po polsku

2020-09-01 19:56 UTC, ziobron approved these changes

2020-09-01 19:57 UTC, merged